### ISSUE TITLE
parameter parsing error

### ISSUE THREAD

**Issue by sukeyisme** [sebasmonia/sqlcmdline#1]
when the -P before -U ,it use -P as user and -U as password ?why?

**Comment by sebasmonia** [comment]
I'm using docopt to parse the command line parameters, if it's not accepting -U and -P in any order that means I need to re-write the --help text to understand both.

**Comment by sebasmonia** [comment]
When calling the script with the parameters "-S a_server -d a_db -P pass -U user", docopt returns the following:
`{'--help': False,
 '-E': False,
 '-P': True,
 '-S': 'a_server',
 '-U': True,
 '-d': 'a_db',
 '-h': False,
 '<password>': 'user',
 '<user>': 'pass'}`

I don't know how why it's reversing the parameters. More importantly, I don't see a way to tell if the params need to be reversed,

**Comment by sebasmonia** [comment]
Fixed in commit https://github.com/sebasmonia/sqlcmdline/commit/8ef55aa3b63860c01295478e372408553fbc37f3
